### ISSUE TITLE
Is this specific to python 3.6? 

### ISSUE THREAD

**Issue by jonocarroll** [gigamonkey/jira-db#1]
https://github.com/gigamonkey/jira-db/blob/93caa0aca4fd35484cd201593a6dfa4ee9f3cd6c/Pipfile#L20

Thank you for sharing the source - I'm happy to have a play and see if I can get it working with our corporate instance. I was not able to install this without changing the version to 3.7 which is what I have installed. Is this likely to cause any issues you can think of?

**Comment by gigamonkey** [comment]
That's fine. I probably just picked 3.6 because that's what I had installed when I wrote this. Given semver, etc. it should be safe to bump to any newer 3.x
